name: deploy node app to servB
on:
  push:
    branches:
      - main
    paths:
      - 'backend-B/**'
      - '!.env.example'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to remote server
        run: |
          rsync -avz --delete --exclude='node_modules' -e "ssh -p ${{ secret.UE_SERVER_PORT }} -o StrictHostKeyChecking=no" backend-B/ ${{ secrets.UE_USER_LOGIN }}@${{ secrets.UE_SERVER_IP }}:/home/enphili/tmdb_api
